/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "ABPeoplePickerNavigationControllerDelegate.h"

@protocol ABPeoplePickerNavigationControllerPrivateMemberCellDelegate <ABPeoplePickerNavigationControllerDelegate>

@optional
- (BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2 property:(int)arg3 identifier:(int)arg4 withMemberCell:(id)arg5;
- (BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2 withLinkedPeople:(struct __CFArray *)arg3 memberCell:(id)arg4;
@end

