/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class AVController, NSArray, NSDictionary;

@interface AudioDeviceController : NSObject
{
    id _delegate;
    AVController *_avController;
    NSDictionary *_pickedRoute;
    NSArray *_pickableRoutes;
}

- (void)callAudioRouteChangedEventHandler:(id)arg1;
- (void)_registerForAVControllerNotifications;
- (void)_pickableRoutesChanged;
- (void)_mediaServerDied;
- (BOOL)_routeIsHandset:(id)arg1;
- (BOOL)_routeIsDefault:(id)arg1;
- (BOOL)_routeIsReceiver:(id)arg1;
- (BOOL)_routeIsSpeaker:(id)arg1;
- (BOOL)_routeIsAirTunes:(id)arg1;
- (BOOL)_routeIsAirPlayMirroring:(id)arg1;
- (BOOL)_routeIsBlueToothLEA:(id)arg1;
- (BOOL)isAirPlayMirroring;
- (void)_pickRoute:(id)arg1;
- (id)_pickableRoutes;
- (id)_pickedRoute;
- (void)pickRouteAtIndex:(unsigned int)arg1;
- (id)routeNameAtIndex:(unsigned int)arg1 isPicked:(char *)arg2;
- (BOOL)audioCategoryIsTTY;
- (BOOL)receiverRouteIsPicked;
- (BOOL)speakerRouteIsPicked;
- (void)clearCachedRoutes;
- (void)restorePickedRoute;
- (BOOL)pickRouteWithUID:(id)arg1;
- (BOOL)pickDefaultRoute;
- (BOOL)pickHandsetRoute;
- (BOOL)pickSpeakerRoute;
- (BOOL)handsetRouteAvailable;
- (BOOL)speakerRouteAvailable;
- (int)numberOfAudioRoutes;
- (BOOL)auxiliaryAudioRoutesAvailable;
- (void)setDelegate:(id)arg1;
- (void)invalidateAVController;
- (void)setAVController:(id)arg1;
- (void)dealloc;
- (id)init;

@end

