/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UITableView.h"

@interface ConferenceManagementTable : UITableView
{
}

- (void)completeRowDeletionAnimation;
- (void)animateDeletionOfRowWithCell:(id)arg1 viaEdge:(unsigned int)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

