/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol DialerLCDFieldProtocol <NSObject>
- (void)setDelegate:(id)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (BOOL)highlighted;
- (void)setInCallMode:(BOOL)arg1;
- (BOOL)inCallMode;
- (void)deleteCharacter;
- (void)setText:(id)arg1 needsFormat:(BOOL)arg2;
- (id)text;

@optional
- (void)setText:(id)arg1 needsFormat:(BOOL)arg2 name:(id)arg3 label:(id)arg4;
- (void)setName:(id)arg1 numberLabel:(id)arg2;
@end

