/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol DialerViewDelegate <NSObject>

@optional
- (void)dialerViewPhoneNumberWasTapped:(id)arg1;
- (void)dialerView:(id)arg1 stringWasPasted:(id)arg2;
- (void)dialerViewTextDidChange:(id)arg1;
@end

