/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "TPLCDView.h"

@class UIButton;

@interface InCallLCDField : TPLCDView
{
    UIButton *_button;
    id _delegate;
    unsigned int _textIsPlaceholder:1;
    unsigned int _buttonIsDelete:1;
}

- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (struct CGRect)textFrame;
- (id)unformattedText;
- (id)text;
- (void)setText:(id)arg1;
- (void)setPlaceholderText:(id)arg1 animating:(BOOL)arg2;
- (void)setShowsDeleteButton:(BOOL)arg1;
- (void)_deleteButtonClicked:(id)arg1;
- (void)_sendButtonClicked:(id)arg1;
- (BOOL)showsSendButton;
- (void)setShowsSendButton:(BOOL)arg1;
- (void)_showButtonWithTitle:(id)arg1 action:(SEL)arg2;
- (void)_removeButton;
- (void)_updateButton;
- (void)setDelegate:(id)arg1;
- (void)dealloc;

@end

