/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PhoneApplication.h"

@class TUCall;

@interface MobilePhoneApplication : PhoneApplication
{
    BOOL _outstandingDecline;
    TUCall *_outstandingDeclineCall;
}

@property(retain) TUCall *outstandingDeclineCall; // @synthesize outstandingDeclineCall=_outstandingDeclineCall;
@property BOOL outstandingDecline; // @synthesize outstandingDecline=_outstandingDecline;
- (BOOL)showsPhoneVoicemail;
- (BOOL)dialerIsNumericOnly;
- (BOOL)showsPhoneDialer;
- (BOOL)badgesMissedFaceTime;
- (BOOL)badgesMissedFaceTimeAudio;
- (BOOL)badgesMissedTelephonyCalls;
- (BOOL)showsFaceTimeRecents;
- (BOOL)showsFaceTimeAudioRecents;
- (BOOL)showsTelephonyRecents;
- (BOOL)showsFaceTimeFavorites;
- (BOOL)showsFaceTimeAudioFavorites;
- (BOOL)showsTelephonyFavorites;
- (BOOL)showsFaceTimeAudio;
- (BOOL)showsFaceTime;
- (BOOL)showsTelephonyCalls;
- (int)defaultAction;
- (BOOL)showSplashScreenOnSignin;
- (BOOL)tabBarCanSlide;
- (BOOL)tabBarFillsScreen;
- (BOOL)contentViewCanRotate;
- (BOOL)alwaysShowVideoConferenceController;
- (BOOL)usesBlendModes;
- (int)addressBookUIStyle;
- (int)wizardGlobalAppearanceStyle;
- (unsigned int)userInterfaceStyle;
- (void)_incomingCallEnded;
- (void)_stopCaringAboutDecline;
- (void)_handlePhoneAppHeardAboutDecline;
- (void)handleResumeEvent:(struct __GSEvent *)arg1;
- (void)dealloc;
- (void)applicationDidFinishLaunching:(id)arg1;
- (BOOL)_isIPad;
- (id)_keyWindowForScreen:(id)arg1;

@end

