/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "DialerLCDFieldDelegate.h"

@class UIControl, UIView<DialerLCDFieldProtocol>, UIView<TPDialerKeypadProtocol>;

@interface PHAbstractDialerView : UIView <DialerLCDFieldDelegate>
{
    BOOL _inCallMode;
    UIView<DialerLCDFieldProtocol> *_lcdView;
    UIView<TPDialerKeypadProtocol> *_phonePadView;
    id <DialerViewDelegate> _delegate;
    UIControl *_addContactButton;
    UIControl *_callButton;
    UIControl *_deleteButton;
}

@property(retain, nonatomic) UIControl *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(retain, nonatomic) UIControl *callButton; // @synthesize callButton=_callButton;
@property(retain, nonatomic) UIControl *addContactButton; // @synthesize addContactButton=_addContactButton;
@property(nonatomic) id <DialerViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIView<TPDialerKeypadProtocol> *phonePadView; // @synthesize phonePadView=_phonePadView;
@property(retain, nonatomic) UIView<DialerLCDFieldProtocol> *lcdView; // @synthesize lcdView=_lcdView;
@property(nonatomic) BOOL inCallMode; // @synthesize inCallMode=_inCallMode;
- (void)dialerField:(id)arg1 stringWasPasted:(id)arg2;
- (void)dialerLCDFieldTextDidChange:(id)arg1;
- (void)dealloc;

@end

