/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "ABPeoplePickerNavigationController.h"

#import "ABPeoplePickerNavigationControllerDelegate.h"
#import "PhoneTabViewController.h"

@interface PHAddressBookController : ABPeoplePickerNavigationController <PhoneTabViewController, ABPeoplePickerNavigationControllerDelegate>
{
    int _abuiStyle;
}

+ (id)defaultPNGName;
+ (id)tabBarIconName;
+ (CDStruct_f8b960e9)badge;
+ (int)tabBarSystemItem;
+ (int)tabViewType;
@property int abuiStyle; // @synthesize abuiStyle=_abuiStyle;
- (void)_applicationDeactivated;
- (void)_restoreState;
- (void)_saveState;
@property void *savedPerson; // @dynamic savedPerson;
@property(readonly) BOOL shouldSaveAndRestoreState; // @dynamic shouldSaveAndRestoreState;
- (BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2 property:(int)arg3 identifier:(int)arg4;
- (BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2;
- (void)peoplePickerNavigationControllerDidCancel:(id)arg1;
- (void)handleURL:(id)arg1;
- (void)prepareForSnapshot;
- (BOOL)shouldSnapshot;
- (BOOL)tabBarControllerShouldSelectViewController:(id)arg1;
- (void)presentViewController:(id)arg1 animated:(BOOL)arg2 completion:(id)arg3;
- (void)pushViewController:(id)arg1 animated:(BOOL)arg2;
- (void)applicationWillSuspend;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (void)_updatePickerBanner:(id)arg1;
- (void)_updatePickerPhoneNumber:(id)arg1;
- (void)dealloc;
- (id)initWithStyle:(int)arg1;

@end

