/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSNumber, NSObject<PHAudioPlayerDataSource>, NSTimer, PHVoicemailAudioController;

@interface PHAudioPlayer : NSObject
{
    PHVoicemailAudioController *_audioController;
    NSNumber *_seekToTime;
    BOOL _isPlaying;
    BOOL _isPlayable;
    BOOL _progressiveDurationAvailable;
    NSObject<PHAudioPlayerDataSource> *_dataSource;
    float _elapsedTime;
    float _playableTime;
    float _totalTime;
    id <PHAudioPlayerDelegate> _audioPlayerDelegate;
    float _progressBarWidth;
    NSTimer *_delayedPlaybackTimer;
    NSTimer *_progressUpdateTimer;
    unsigned int _currentFileSize;
    unsigned int _expectedFileSize;
}

+ (id)sharedAudioPlayer;
@property BOOL progressiveDurationAvailable; // @synthesize progressiveDurationAvailable=_progressiveDurationAvailable;
@property unsigned int expectedFileSize; // @synthesize expectedFileSize=_expectedFileSize;
@property unsigned int currentFileSize; // @synthesize currentFileSize=_currentFileSize;
@property(nonatomic) NSTimer *progressUpdateTimer; // @synthesize progressUpdateTimer=_progressUpdateTimer;
@property(nonatomic) NSTimer *delayedPlaybackTimer; // @synthesize delayedPlaybackTimer=_delayedPlaybackTimer;
@property(nonatomic) float progressBarWidth; // @synthesize progressBarWidth=_progressBarWidth;
@property(nonatomic) id <PHAudioPlayerDelegate> audioPlayerDelegate; // @synthesize audioPlayerDelegate=_audioPlayerDelegate;
@property(readonly) PHVoicemailAudioController *audioController; // @synthesize audioController=_audioController;
@property float totalTime; // @synthesize totalTime=_totalTime;
@property float playableTime; // @synthesize playableTime=_playableTime;
@property float elapsedTime; // @synthesize elapsedTime=_elapsedTime;
@property(retain, nonatomic) NSObject<PHAudioPlayerDataSource> *dataSource; // @synthesize dataSource=_dataSource;
@property BOOL isPlayable; // @synthesize isPlayable=_isPlayable;
@property BOOL isPlaying; // @synthesize isPlaying=_isPlaying;
- (void)_proximityStateChanged:(id)arg1;
- (void)_handlePlayableDurationChanged:(id)arg1;
- (void)_updateDurations;
- (void)_forceUpdateProgressiveDataLengths;
- (BOOL)_fileExists:(id)arg1;
- (void)seekToTime:(float)arg1;
- (void)_stopPlayingWithError:(id)arg1;
- (void)stop;
- (void)_updateProgress;
- (BOOL)_updateElapsedTime;
- (void)_setupProgressUpdateTimer;
- (void)_avControllerDied:(id)arg1;
- (void)_avControllerPlaybackInterrupted:(id)arg1;
- (void)_avControllerPlaybackRateChanged:(id)arg1;
- (void)_avControllerPlaybackDidEnd:(id)arg1;
- (void)_avControllerPlaybackStateDidChangeItem:(id)arg1;
- (void)_avControllerTimeJumped:(id)arg1;
- (void)_start;
- (BOOL)_createVoicemailAVItemIfNecessary:(id *)arg1;
- (void)start;
- (void)dealloc;
- (id)init;

@end

