/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@protocol PHAudioRecorderDelegate
- (void)audioRecorderEndedWithFile:(id)arg1 duration:(double)arg2 error:(id)arg3;
- (void)audioRecorderContinuedWithFile:(id)arg1 duration:(double)arg2;
- (void)audioRecorderStartedWithFile:(id)arg1;
@end

