/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PHHandsetDialerView.h"

@interface PHEmergencyHandsetDialerView : PHHandsetDialerView
{
}

- (id)layoutConstraintMetrics;
- (id)newCallButton;
- (id)newNumberPadView;
- (id)newLCDView;
- (void)createConstraints;
- (id)dialerColor;
- (id)initWithFrame:(struct CGRect)arg1;

@end

