/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PHHandsetDialerLCDView.h"

@class PHTextCycleLabel;

@interface PHEmergencyHandsetDialerLCDView : PHHandsetDialerLCDView
{
    PHTextCycleLabel *_emergencyTitleLabel;
}

@property(readonly) PHTextCycleLabel *emergencyTitleLabel; // @synthesize emergencyTitleLabel=_emergencyTitleLabel;
- (void)applyLayoutConstraints;
- (id)newDeleteButton;
- (id)newNameAndLabelView;
- (id)numberLabelFont;
- (id)lcdColor;
- (float)frameHeight;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 forDialerType:(int)arg2;

@end

