/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBUIEmergencyCallServiceViewController.h"

#import "DialerViewDelegate.h"
#import "PhoneBaseViewController.h"
#import "TPDialerKeypadDelegate.h"

@class NSTimer, PHHandsetDialerLCDView, PHHandsetDialerView, UIButton;

@interface PHEmergencyDialerViewController : SBUIEmergencyCallServiceViewController <PhoneBaseViewController, TPDialerKeypadDelegate, DialerViewDelegate>
{
    BOOL _inApplicationMode;
    BOOL _callEnding;
    short _currentState;
    PHHandsetDialerLCDView *_lcdView;
    PHHandsetDialerView *_dialerView;
    NSTimer *_callDurationTimer;
    UIButton *_backButton;
    UIButton *_endButton;
}

+ (id)defaultPNGName;
+ (int)statusBarStyle;
+ (int)viewType;
@property BOOL callEnding; // @synthesize callEnding=_callEnding;
@property(nonatomic) short currentState; // @synthesize currentState=_currentState;
@property(retain) UIButton *endButton; // @synthesize endButton=_endButton;
@property(retain) UIButton *backButton; // @synthesize backButton=_backButton;
@property NSTimer *callDurationTimer; // @synthesize callDurationTimer=_callDurationTimer;
@property(retain) PHHandsetDialerView *dialerView; // @synthesize dialerView=_dialerView;
@property(retain) PHHandsetDialerLCDView *lcdView; // @synthesize lcdView=_lcdView;
@property BOOL inApplicationMode; // @synthesize inApplicationMode=_inApplicationMode;
- (void)dialEmergencyCall;
- (void)updateEmergencyTitleLabelForCallDuration;
- (id)currentCallStatusStringForDisplay;
- (void)phonePad:(id)arg1 dialerCharacterButtonWasHeld:(unsigned int)arg2;
- (void)phonePad:(id)arg1 replaceLastDigitWithString:(id)arg2;
- (void)phonePadDidEndSounds:(id)arg1;
- (void)phonePadWillBeginSounds:(id)arg1;
- (void)phonePad:(id)arg1 keyUp:(BOOL)arg2;
- (void)phonePad:(id)arg1 keyDown:(BOOL)arg2;
- (void)phonePadDeleteLastDigit:(id)arg1;
- (void)phonePad:(id)arg1 appendString:(id)arg2;
- (void)callStatusChangedNotification:(id)arg1;
- (void)transitionInFromViewType:(int)arg1 animated:(BOOL)arg2 completionBlock:(id)arg3;
- (void)prepareForTransitionInFromViewType:(int)arg1 animated:(BOOL)arg2;
- (void)handleURL:(id)arg1;
- (void)prepareToHandleURL:(id)arg1;
- (void)updateViewControllerForOrientation:(int)arg1;
- (void)prepareForSnapshot;
- (BOOL)shouldSnapshot;
- (BOOL)shouldDisableEdgeClip;
- (void)continueCyclingEmergencyTitleLabel;
- (void)setCurrentState:(short)arg1 animated:(BOOL)arg2;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)backButtonTapped:(id)arg1;
- (void)callButtonTapped:(id)arg1;
- (void)endButtonTapped:(id)arg1;
- (void)deleteButtonTapped:(id)arg1;
- (void)dealloc;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

