/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PhoneViewController.h"

#import "ABPeoplePickerNavigationControllerPrivateMemberCellDelegate.h"
#import "ABUnknownPersonViewControllerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class ABFavoritesEntry, ABPeoplePickerNavigationController, NSDictionary, UIActionSheet, UITableView, _UIContentUnavailableView;

@interface PHFavoritesViewController : PhoneViewController <UITableViewDataSource, UITableViewDelegate, ABUnknownPersonViewControllerDelegate, ABPeoplePickerNavigationControllerPrivateMemberCellDelegate, UIActionSheetDelegate>
{
    UITableView *_table;
    _UIContentUnavailableView *_noContentView;
    ABPeoplePickerNavigationController *_peoplePickerController;
    ABFavoritesEntry *_selectedABFavoritesEntry;
    UIActionSheet *_disambiguationSheet;
    NSDictionary *_disambiguationSheetContext;
    unsigned int _suspended:1;
    unsigned int _ignoreFavoritesDidChangeNotification:1;
    unsigned int _postponeTableReloadFromFavoritesChange:1;
    unsigned int _needsTableReloadFromFavoritesChange:1;
}

+ (id)tabBarIconName;
+ (int)tabBarSystemItem;
+ (int)tabViewType;
+ (BOOL)requiresNavigationControllerContainer;
- (void)unknownPersonViewController:(id)arg1 didResolveToPerson:(void *)arg2;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (void)accessoryButtonTapped:(id)arg1 withEvent:(id)arg2;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3;
- (BOOL)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)deleteButtonPressedForIndexPath:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)selectedIndex;
- (int)absoluteIndexOfFilteredIndex:(int)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)_addButtonClicked:(id)arg1;
- (BOOL)peoplePickerNavigationController:(id)arg1 shouldAllowSelectingPersonWithRecordID:(int)arg2;
- (BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2 property:(int)arg3 identifier:(int)arg4;
- (BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2 property:(int)arg3 identifier:(int)arg4 withMemberCell:(id)arg5;
- (BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2;
- (BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void *)arg2 withLinkedPeople:(struct __CFArray *)arg3 memberCell:(id)arg4;
- (void)peoplePickerNavigationController:(id)arg1 insertEditorDidConfirm:(BOOL)arg2 forPerson:(void *)arg3;
- (BOOL)peoplePickerNavigationController:(id)arg1 shouldShowInsertEditorForPerson:(void *)arg2 insertProperty:(int *)arg3 copyInsertValue:(id *)arg4 copyInsertLabel:(id *)arg5;
- (void)peoplePickerNavigationControllerDidCancel:(id)arg1;
- (void)dismissPeoplePicker;
- (void)_addEntryFromPeoplePickerForPerson:(void *)arg1 property:(int)arg2 identifier:(int)arg3 animateView:(id)arg4;
- (BOOL)usesPersonBasedFavorites;
- (id)buttonTitlesForPossibleFavoriteTypes:(id)arg1;
- (id)possibleFavoriteTypesForProperty:(int)arg1;
- (void)_addEntryFromPeoplePickerForPerson:(void *)arg1 property:(int)arg2 identifier:(int)arg3 animateView:(id)arg4 favoritesEntryType:(int)arg5;
- (void)showCardViewerForPerson:(void *)arg1 withTitle:(id)arg2 animate:(BOOL)arg3;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)_updateNavButtons;
- (void)_favoritesManagerSignificantChangeNotification:(id)arg1;
- (void)restoreState;
- (BOOL)shouldSnapshot;
- (void)unloadView;
- (void)didReceiveMemoryWarning;
- (void)savePreferences;
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (void)_updateContentView;
@property(readonly) _UIContentUnavailableView *noContentView;
- (BOOL)showsNoContentView;
@property(readonly) UITableView *table;
- (void)_handleContentSizeCategoryDidChange:(id)arg1;
- (void)_handleFavoritesShowsContactPhotosChanged:(id)arg1;
- (void)dealloc;
- (id)init;

@end

