/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "ABFavoritesEntry.h"

@class UIImage;

@interface PHFavoritesEntry : ABFavoritesEntry
{
    UIImage *_thumbnail;
    BOOL _isPersonImage;
}

+ (id)sharedMonogrammer;
+ (BOOL)_usesFlatImages;
@property(nonatomic) BOOL isPersonImage; // @synthesize isPersonImage=_isPersonImage;
- (void)dealloc;
- (id)thumbnail;
- (void)loadThumbnailIfNecessary;

@end

