/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface PHFavoritesManager : NSObject
{
}

+ (BOOL)dialFavoriteEntry:(id)arg1;
+ (void)recacheIdentitiesSoon;
+ (void)save;
+ (id)starkFavorites;
+ (id)currentFavorites;
+ (id)_favoritesWithPredicate:(id)arg1;
+ (id)allFavorites;
+ (id)predicateForFaceTimeEntries;
+ (id)predicateForFaceTimeAudioEntries;
+ (id)predicateForTelephonyEntries;
+ (void)_phoneApplicationAddressBookChangedNotification:(id)arg1;
+ (void)_ftcServiceAvailabilityDidChangeNotification:(id)arg1;
+ (void)_abfavoritesListChangedNotification:(id)arg1;
+ (void)_abFavoritesEntryChangedNotification:(id)arg1;
+ (void)_clearCachedFavorites;
+ (void)initialize;

@end

