/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "DialerLCDFieldProtocol.h"
#import "UIGestureRecognizerDelegate.h"

@class NSLayoutConstraint, PHHandsetDialerNameLabelView, UIButton, UILabel, UILongPressGestureRecognizer;

@interface PHHandsetDialerLCDView : UIView <DialerLCDFieldProtocol, UIGestureRecognizerDelegate>
{
    BOOL _numberAccoutrementsVisible;
    BOOL _highlighted;
    BOOL _inCallMode;
    int _dialerType;
    UIButton *_deleteButton;
    id <DialerLCDFieldDelegate> _delegate;
    PHHandsetDialerNameLabelView *_nameAndLabelView;
    UILabel *_numberLabel;
    UILongPressGestureRecognizer *_longPressRecognizer;
    NSLayoutConstraint *_numberLabelVerticalConstraint;
    NSLayoutConstraint *_deleteButtonVerticalConstraint;
}

@property(retain) NSLayoutConstraint *deleteButtonVerticalConstraint; // @synthesize deleteButtonVerticalConstraint=_deleteButtonVerticalConstraint;
@property(retain) NSLayoutConstraint *numberLabelVerticalConstraint; // @synthesize numberLabelVerticalConstraint=_numberLabelVerticalConstraint;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPressRecognizer; // @synthesize longPressRecognizer=_longPressRecognizer;
@property(retain, nonatomic) UILabel *numberLabel; // @synthesize numberLabel=_numberLabel;
@property(retain) PHHandsetDialerNameLabelView *nameAndLabelView; // @synthesize nameAndLabelView=_nameAndLabelView;
@property(nonatomic) BOOL inCallMode; // @synthesize inCallMode=_inCallMode;
@property(nonatomic) BOOL highlighted; // @synthesize highlighted=_highlighted;
@property(nonatomic) id <DialerLCDFieldDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain) UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(nonatomic) int dialerType; // @synthesize dialerType=_dialerType;
- (void)applyLayoutConstraints;
- (id)newDeleteButton;
- (id)newNameAndLabelView;
- (id)lcdColor;
- (void)handleLongPress:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)paste:(id)arg1;
- (void)copy:(id)arg1;
- (BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (BOOL)resignFirstResponder;
- (BOOL)canBecomeFirstResponder;
- (void)_displayCallout;
- (void)_menuDidHide:(id)arg1;
- (void)_menuWillHide:(id)arg1;
- (void)_requestMakeCutCopyPasteCalloutVisible:(BOOL)arg1;
- (void)_makeCalloutVisible:(BOOL)arg1;
- (void)_setHighlighted:(BOOL)arg1;
- (void)setNumberAccoutrementsVisible:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setName:(id)arg1 numberLabel:(id)arg2;
- (void)deleteCharacter;
- (void)setText:(id)arg1 needsFormat:(BOOL)arg2;
- (void)setText:(id)arg1 needsFormat:(BOOL)arg2 name:(id)arg3 label:(id)arg4;
- (id)text;
- (void)dealloc;
- (struct CGSize)intrinsicContentSize;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 forDialerType:(int)arg2;
- (id)numberLabelFont;
- (float)spacingBetweenLCDBottomAndNameView;
- (float)frameHeight;
- (float)numberLabelMinimumFontSize;
- (float)numberLabelMaximumFontSize;
- (float)deleteButtonVerticalConstantValue;
- (float)numberLabelVerticalConstantValue;

@end

