/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIControl.h"

@class UILabel;

@interface PHHandsetDialerNameLabelView : UIControl
{
    BOOL _isShowingAddToContactsLabel;
    UILabel *_nameAndLabelLabel;
    UILabel *_addToContactsLabel;
}

@property BOOL isShowingAddToContactsLabel; // @synthesize isShowingAddToContactsLabel=_isShowingAddToContactsLabel;
@property(retain) UILabel *addToContactsLabel; // @synthesize addToContactsLabel=_addToContactsLabel;
@property(retain) UILabel *nameAndLabelLabel; // @synthesize nameAndLabelLabel=_nameAndLabelLabel;
- (void)showAddToContactsLabel;
- (void)showName:(id)arg1 label:(id)arg2 animated:(BOOL)arg3;
- (void)setHighlighted:(BOOL)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)dealloc;
- (id)textColorForHighlightedState:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

