/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

#import "PhoneTabViewController.h"

@interface PhoneViewController : UIViewController <PhoneTabViewController>
{
}

+ (BOOL)tabBarIconImageFinished:(id *)arg1 selectedImage:(id *)arg2 forTabBarItemName:(id)arg3;
+ (void)cacheFinishedTabBarIconImage:(id)arg1 finishedSelectedTabBarIconImage:(id)arg2 withTabBarItemName:(id)arg3;
+ (id)defaultPNGName;
+ (id)tabBarIconName;
+ (CDStruct_f8b960e9)badge;
+ (int)tabViewType;
+ (void)initializeIconAndTitle:(id)arg1;
- (void)_prepareForLoadView;
- (void)viewWillUnload;
- (void)_loadOffsetDefaultForKey:(id)arg1 withScrollView:(id)arg2;
- (void)_saveOffsetDefaultForKey:(id)arg1 withScrollView:(id)arg2;
- (void)savePreferences;
- (void)handleURL:(id)arg1;
- (void)prepareForSnapshot;
- (BOOL)shouldSnapshot;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)init;

@end

