/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class UIImage, UIImageView, UITransitionView, _UIBackdropView;

@interface PhoneDesktopView : UIView
{
    UIImageView *_imageView;
    UIImage *_wallpaperImage;
    UIImage *_queuedImage;
    BOOL _animatingTransition;
    _UIBackdropView *_backdropView;
    UITransitionView *_wallpaperContainer;
}

@property(retain) UITransitionView *wallpaperContainer; // @synthesize wallpaperContainer=_wallpaperContainer;
@property(retain) _UIBackdropView *backdropView; // @synthesize backdropView=_backdropView;
@property(readonly, getter=isAnimatingTransition) BOOL animatingTransition; // @synthesize animatingTransition=_animatingTransition;
- (void)transitionToQueuedImage;
- (void)reallyTransitionToImage:(id)arg1 animated:(BOOL)arg2;
- (void)transitionToImage:(id)arg1 animated:(BOOL)arg2;
- (id)initWithFrame:(struct CGRect)arg1 image:(id)arg2;
- (void)transitionViewDidComplete:(id)arg1 fromView:(id)arg2 toView:(id)arg3;
- (double)durationForTransition:(int)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

