/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol PhoneBaseViewController <NSObject>
+ (id)defaultPNGName;
+ (int)statusBarStyle;
+ (int)viewType;
- (void)handleURL:(id)arg1;
- (void)prepareForSnapshot;
- (BOOL)shouldSnapshot;
- (BOOL)shouldDisableEdgeClip;

@optional
- (void)transitionInFromViewType:(int)arg1 animated:(BOOL)arg2 completionBlock:(id)arg3;
- (void)prepareForTransitionInFromViewType:(int)arg1 animated:(BOOL)arg2;
- (void)updateViewControllerForOrientation:(int)arg1;
- (void)prepareToHandleURL:(id)arg1;
@end

