/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

#import "CNFRegWizardControllerDelegate.h"
#import "UITabBarControllerDelegate.h"

@class CNFRegWizardController, InCallController, PHEmergencyDialerViewController, PhoneContentView, PhoneTabBarController, VideoConferenceController, _UIBackdropView;

@interface PhoneRootViewController : UIViewController <CNFRegWizardControllerDelegate, UITabBarControllerDelegate>
{
    int _currentViewType;
    PhoneContentView *_contentView;
    PhoneTabBarController *_tabBarViewController;
    CNFRegWizardController *_faceTimeRegistrationViewController;
    InCallController *_inCallViewController;
    VideoConferenceController *_videoConferenceViewController;
    PHEmergencyDialerViewController *_emergencyDialerViewController;
    BOOL _faceTimeRegistrationViewIsShowing;
    BOOL _disableAutomaticAppearEvents;
    BOOL _inTransitionBetweenViewTypes;
    BOOL _returnToTabViewOnSuspendIfNeeded;
    _UIBackdropView *_backdropView;
}

@property(readonly, nonatomic) _UIBackdropView *backdropView; // @synthesize backdropView=_backdropView;
@property(readonly, nonatomic) BOOL inTransitionBetweenViewTypes; // @synthesize inTransitionBetweenViewTypes=_inTransitionBetweenViewTypes;
@property(readonly, nonatomic) CNFRegWizardController *faceTimeRegistrationViewController; // @synthesize faceTimeRegistrationViewController=_faceTimeRegistrationViewController;
@property(nonatomic) BOOL disableAutomaticAppearEvents; // @synthesize disableAutomaticAppearEvents=_disableAutomaticAppearEvents;
@property(nonatomic) int currentViewType; // @synthesize currentViewType=_currentViewType;
- (void)resetCurrentViewType;
- (void)returnToTabViewForSuspendIfNeeded;
- (void)setupCrossfadeBackToDialingAppWithDelay:(double)arg1;
- (void)tabBarController:(id)arg1 didSelectViewController:(id)arg2;
- (BOOL)tabBarController:(id)arg1 shouldSelectViewController:(id)arg2;
- (void)firstRunControllerDidFinish:(id)arg1 finished:(BOOL)arg2;
- (void)_destroyFirstRunController;
- (void)showFaceTimeFirstRunViewIfNeeded;
- (void)_createFaceTimeFirstRunViewIfNeeded;
- (void)updateFacetimeFirstRunViewKnockouts;
- (void)transitionFromVideoConferenceViewToInCallViewAnimated:(BOOL)arg1 completion:(id)arg2;
- (void)transitionFromVideoConferenceViewToTabViewAnimated:(BOOL)arg1 completion:(id)arg2;
- (void)transitionFromInCallViewToVideoConferenceViewAnimated:(BOOL)arg1 completion:(id)arg2;
- (void)transitionFromInCallViewToTabViewAnimated:(BOOL)arg1 completion:(id)arg2;
- (void)transitionFromTabViewToVideoConferenceViewAnimated:(BOOL)arg1 completion:(id)arg2;
- (void)transitionFromTabViewToInCallViewAnimated:(BOOL)arg1 completion:(id)arg2;
- (void)transitionToView:(int)arg1 animated:(BOOL)arg2 completionBlock:(id)arg3;
- (BOOL)shouldSwitchRootViewToViewType:(int)arg1;
- (void)animateInUI;
- (void)removeViewControllerFromHierarchyIfNecessary:(id)arg1;
- (void)initializeToEmergencyDialerViewAnimated:(BOOL)arg1 completion:(id)arg2;
- (void)initializeToVideoConferenceViewAnimated:(BOOL)arg1 completion:(id)arg2;
- (void)initializeToInCallViewAnimated:(BOOL)arg1 completion:(id)arg2;
- (void)initializeToTabViewAnimated:(BOOL)arg1 completion:(id)arg2;
- (void)hideVideoConferenceBackgroundViewAnimated:(BOOL)arg1;
- (void)showVideoConferenceBackgroundViewAnimated:(BOOL)arg1;
- (void)hideContentViewAnimated:(BOOL)arg1 completionBlock:(id)arg2;
- (void)setContentViewHiddenPosition;
- (void)showContentViewAnimated:(BOOL)arg1 completionBlock:(id)arg2;
- (void)setContentViewNormalPosition;
- (BOOL)isContentViewLoaded;
- (void)setupContentViewFullSize;
- (void)setupContentViewSidebar;
- (void)_ensureProperPositionForContentView;
- (void)_unloadChildViewControllers;
- (void)_unloadViewsForController:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)_applicationSuspended:(id)arg1;
- (void)applicationDidResume;
- (void)applicationWillSuspend;
- (void)_getRotationContentSettings:(CDStruct_af7d35ee *)arg1;
- (BOOL)shouldAutorotate;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)updateChildViewControllersForCurrentOrientation;
@property(readonly, nonatomic) PHEmergencyDialerViewController *emergencyDialerViewController; // @synthesize emergencyDialerViewController=_emergencyDialerViewController;
@property(readonly, nonatomic) VideoConferenceController *videoConferenceViewController; // @synthesize videoConferenceViewController=_videoConferenceViewController;
@property(readonly, nonatomic) InCallController *inCallViewController; // @synthesize inCallViewController=_inCallViewController;
@property(readonly, nonatomic) PhoneTabBarController *tabBarViewController; // @synthesize tabBarViewController=_tabBarViewController;
- (id)viewControllerForRootViewType:(int)arg1;
- (void)dealloc;
- (void)viewDidUnload;
- (void)loadView;
- (id)init;
- (BOOL)automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers;
@property(readonly, nonatomic) PhoneContentView *contentView;
@property(readonly, nonatomic) CDStruct_f8b960e9 applicationBadge;

@end

