/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UINavigationController.h"

#import "PhoneTabViewController.h"

@class UIViewController<PhoneTabViewController>;

@interface PhoneNavigationController : UINavigationController <PhoneTabViewController>
{
    UIViewController<PhoneTabViewController> *_rootController;
}

+ (BOOL)_isViewSizeFullScreen:(id)arg1 inWindow:(id)arg2;
+ (id)defaultPNGName;
+ (id)tabBarIconImageSelected;
+ (id)tabBarIconImage;
+ (id)tabBarIconName;
+ (CDStruct_f8b960e9)badge;
+ (int)tabViewType;
- (void)handleURL:(id)arg1;
- (void)prepareForSnapshot;
- (BOOL)shouldSnapshot;
- (void)presentViewController:(id)arg1 animated:(BOOL)arg2 completion:(id)arg3;
- (void)pushViewController:(id)arg1 animated:(BOOL)arg2;
- (void)setViewControllers:(id)arg1;
- (id)rootViewController;
- (void)_updateRootViewController;
- (void)dealloc;
- (id)initWithRootViewController:(id)arg1;

@end

