/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"
#import "PhoneBadgeable.h"

@protocol PhoneTabViewController <NSObject, PhoneBadgeable>
+ (id)tabBarIconName;
+ (id)defaultPNGName;
+ (int)tabViewType;
- (void)handleURL:(id)arg1;
- (void)prepareForSnapshot;
- (BOOL)shouldSnapshot;

@optional
+ (BOOL)requiresNavigationControllerContainer;
+ (id)tabBarIconImageSelected;
+ (id)tabBarIconImage;
+ (id)tabBarIconImageName;
+ (int)tabBarSystemItem;
- (BOOL)tabBarControllerShouldSelectViewController:(id)arg1;
- (void)tabBarDidSelectViewController;
@end

