/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UITableViewCell.h"

@class NSArray, NSDictionary, NSLayoutConstraint, PHRecentCall, UIDateLabel, UIImageView, UILabel;

@interface PHRecentsCell : UITableViewCell
{
    UILabel *_callerNameLabel;
    UILabel *_callerLabelLabel;
    UILabel *_callerCountLabel;
    UIDateLabel *_callerDateLabel;
    UIImageView *_callTypeIconView;
    NSDictionary *_allViewsDictionary;
    long _buildConstraintsOnceToken;
    NSLayoutConstraint *_topConstraint;
    NSLayoutConstraint *_bottomConstraint;
    PHRecentCall *_call;
    NSArray *_calculatedConstraints;
}

+ (id)allMetrics;
+ (float)height;
+ (float)editingMarginWidth;
+ (float)marginWidth;
+ (id)_sharedOutgoingSelectedFaceTimeImage;
+ (id)_sharedOutgoingFaceTimeImage;
+ (id)_sharedOutgoingSelectedCallImage;
+ (id)_sharedOutgoingCallImage;
@property(retain, nonatomic) NSArray *calculatedConstraints; // @synthesize calculatedConstraints=_calculatedConstraints;
@property(retain, nonatomic) PHRecentCall *call; // @synthesize call=_call;
- (void)_updateFonts;
- (void)_handleContentSizeDidChange:(id)arg1;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)updateConstraints;
- (void)_recalculateConstraints;
- (void)_buildConstraints;
@property(readonly) NSDictionary *allMetrics; // @dynamic allMetrics;
@property(readonly) NSDictionary *allViews; // @dynamic allViews;
@property(readonly) int count; // @dynamic count;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

