/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PHRecentsPersonHeaderView.h"

@interface PHRecentsPersonFaceTimeHeaderView : PHRecentsPersonHeaderView
{
}

- (id)newSummaryViewForRecentCall:(id)arg1 occurrenceDate:(id)arg2 type:(int)arg3 duration:(double)arg4 category:(int)arg5 dataUsage:(double)arg6;

@end

