/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UISegmentedControl.h"

@interface PHRecentsToggleButton : UISegmentedControl
{
}

- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithWidth:(float)arg1 leftTitle:(id)arg2 rightTitle:(id)arg3;

@end

