/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class NSArray, PHRecentCall;

@interface PHRecentsPersonHeaderView : UIView
{
    PHRecentCall *_recentCall;
    NSArray *_dateLabels;
    NSArray *_summaries;
    float _intrinsicContentHeight;
}

+ (id)headerViewWithFrame:(struct CGRect)arg1 recentCall:(id)arg2;
@property float intrinsicContentHeight; // @synthesize intrinsicContentHeight=_intrinsicContentHeight;
@property(retain) NSArray *summaries; // @synthesize summaries=_summaries;
@property(retain) NSArray *dateLabels; // @synthesize dateLabels=_dateLabels;
@property(readonly) PHRecentCall *recentCall; // @synthesize recentCall=_recentCall;
- (void)setFrame:(struct CGRect)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)_buildView;
- (void)dealloc;
- (id)_initWithFrame:(struct CGRect)arg1 recentCall:(id)arg2;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)newSummaryViewForRecentCall:(id)arg1 occurrenceDate:(id)arg2 type:(int)arg3 duration:(double)arg4 category:(int)arg5 dataUsage:(double)arg6;

@end

