/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PhoneViewController.h"

#import "ABUnknownPersonViewControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, PHRecentCall, PHRecentsManager, PHRecentsToggleButton, UITableView;

@interface PHRecentsViewController : PhoneViewController <ABUnknownPersonViewControllerDelegate, UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_table;
    PHRecentsToggleButton *_toggleButton;
    int _tableFilterMode;
    PHRecentCall *_call;
    unsigned int _isRegisteredForActiveNotifications:1;
    NSArray *indexPathsForMissedCalls;
    NSArray *indexPathsForNormalCalls;
    PHRecentsManager *_recentsManager;
}

+ (CDStruct_f8b960e9)badge;
+ (id)tabBarIconName;
+ (int)tabBarSystemItem;
+ (int)tabViewType;
+ (BOOL)requiresNavigationControllerContainer;
@property(retain) PHRecentsManager *recentsManager; // @synthesize recentsManager=_recentsManager;
@property int _tableFilterMode; // @synthesize _tableFilterMode;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)_clearButtonTapped:(id)arg1;
- (void)unknownPersonViewController:(id)arg1 didResolveToPerson:(void *)arg2;
- (void)_phoneApplicationDidChangeTabBarSelectionNotification:(id)arg1;
- (void)_applicationSuspendedNotification:(id)arg1;
- (void)_applicationResumedNotification:(id)arg1;
- (void)_recentsManagerCallDeletedNotification:(id)arg1;
- (void)_recentsManagerSignificantChangeNotification:(id)arg1;
- (void)_significantTimeChangeNotification:(id)arg1;
- (void)_reloadTableViewAndNavigationBar;
- (void)_handleContentSizeCategoryDidChange:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (void)accessoryButtonTapped:(id)arg1 withEvent:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)callAtTableViewIndex:(int)arg1;
- (int)rowCountForCurrentTableMode;
@property(readonly) NSArray *indexPathsForNormalCalls; // @synthesize indexPathsForNormalCalls;
@property(readonly) NSArray *indexPathsForMissedCalls; // @synthesize indexPathsForMissedCalls;
- (void)resetCachedIndexes;
- (void)unloadView;
- (void)didReceiveMemoryWarning;
- (void)savePreferences;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)_markAllCallsRead;
- (void)_updateNavBarButtons;
- (BOOL)shouldSnapshot;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)showCallDetail:(id)arg1 animate:(BOOL)arg2;
- (void)_filterWasToggled:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)table;

@end

