/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface PHStarkVoicemailManager : NSObject
{
}

+ (BOOL)isVisualVoicemailAvailable;
+ (id)sharedVoicemailManager;
- (id)badgeString;
- (id)voicemailWithID:(long long)arg1;
- (id)trashedVoicemails;
- (id)voicemails;
- (void)voicemailStoreContentsRemovedNotification:(id)arg1;
- (void)voicemailFlagsChangedNotification:(id)arg1;
- (void)onlineStateChangedNotification:(id)arg1;
- (void)voicemailsAddedNotification:(id)arg1;
- (void)dealloc;
- (id)init;

@end

