/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PHStarkGenericViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, PHStarkNoContentBannerView, UITableView;

@interface PHStarkGenericTableViewController : PHStarkGenericViewController <UITableViewDataSource, UITableViewDelegate>
{
    BOOL _tableViewReloadIsRequiredOnViewWillAppear;
    BOOL _viewIsInAppearedState;
    UITableView *_mainTableView;
    PHStarkNoContentBannerView *_noContentBannerView;
}

@property(retain) PHStarkNoContentBannerView *noContentBannerView; // @synthesize noContentBannerView=_noContentBannerView;
@property(readonly) BOOL viewIsInAppearedState; // @synthesize viewIsInAppearedState=_viewIsInAppearedState;
@property BOOL tableViewReloadIsRequiredOnViewWillAppear; // @synthesize tableViewReloadIsRequiredOnViewWillAppear=_tableViewReloadIsRequiredOnViewWillAppear;
@property(retain) UITableView *mainTableView; // @synthesize mainTableView=_mainTableView;
- (void)updateBadgeString;
@property(readonly) NSString *badgeString;
- (id)subtitleForNoContentBanner;
- (id)titleForNoContentBanner;
- (void)setNoContentBannerShown:(BOOL)arg1;
- (void)hardwareControlEventNotification:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)programmaticallySelectRowAtIndexPath:(id)arg1;
- (BOOL)shouldRespondToHardwareControlEvent;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (float)defaultRowHeight;
- (void)loadView;
- (void)applicationBadgeChangedNotification:(id)arg1;
- (id)init;

@end

