/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

#import "PHStarkTelephonyStateMonitorDelegate.h"
#import "UITabBarControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, PHStarkTelephonyStateMonitor, UIView;

@interface PHStarkMainMenuContainerViewController : UIViewController <PHStarkTelephonyStateMonitorDelegate, UITabBarControllerDelegate, UITableViewDelegate, UITableViewDataSource>
{
    NSArray *_rootViewControllerDictionaries;
    UIView *_centralAreaContainerView;
    UIViewController *_selectedViewController;
    PHStarkTelephonyStateMonitor *_telephonyStateMonitor;
}

@property(retain) PHStarkTelephonyStateMonitor *telephonyStateMonitor; // @synthesize telephonyStateMonitor=_telephonyStateMonitor;
@property(retain) UIViewController *selectedViewController; // @synthesize selectedViewController=_selectedViewController;
@property(retain) UIView *centralAreaContainerView; // @synthesize centralAreaContainerView=_centralAreaContainerView;
@property(retain) NSArray *rootViewControllerDictionaries; // @synthesize rootViewControllerDictionaries=_rootViewControllerDictionaries;
- (void)telephonyStateDidChangeToState:(int)arg1;
- (void)_initializeRootViewControllerDictionaries;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (BOOL)tabBarController:(id)arg1 shouldSelectViewController:(id)arg2;
- (void)dealloc;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

