/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class UILabel;

@interface PHStarkLozengeLabel : UIView
{
    BOOL _highlighted;
    UILabel *_label;
}

@property(nonatomic) BOOL highlighted; // @synthesize highlighted=_highlighted;
@property(retain) UILabel *label; // @synthesize label=_label;
- (void)dealloc;
- (struct CGSize)intrinsicContentSize;
- (BOOL)isHighlighted;
- (id)init;

@end

