/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PHStarkGenericTableViewCell.h"

@class NSLayoutConstraint, UILabel;

@interface PHStarkFavoritesTableViewCell : PHStarkGenericTableViewCell
{
    UILabel *_nameLabel;
    UILabel *_phoneNumberTypeLabel;
    NSLayoutConstraint *_nameLabelBaselineLayoutConstraint;
}

@property(retain) NSLayoutConstraint *nameLabelBaselineLayoutConstraint; // @synthesize nameLabelBaselineLayoutConstraint=_nameLabelBaselineLayoutConstraint;
@property(retain) UILabel *phoneNumberTypeLabel; // @synthesize phoneNumberTypeLabel=_phoneNumberTypeLabel;
@property(retain) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void)setRepresentedFavorite:(id)arg1;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

