/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

@class UILabel, UITableView;

@interface PHStarkActionSheetViewController : UIViewController
{
    UILabel *_headerLabel;
    UITableView *_tableView;
}

@property(retain) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain) UILabel *headerLabel; // @synthesize headerLabel=_headerLabel;
- (void)_physicalButtonsBegan:(id)arg1 withEvent:(id)arg2;
- (void)dealloc;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;

@end

