/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface PHStarkTelephonyStateMonitor : NSObject
{
    id <PHStarkTelephonyStateMonitorDelegate> _delegate;
    int _state;
}

@property(nonatomic) int state; // @synthesize state=_state;
@property id <PHStarkTelephonyStateMonitorDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_phoneApplicationDisplayedCallsChangedNotification:(id)arg1;
- (void)stopMonitoringTelephonyState;
- (void)startMonitoringTelephonyState;
- (int)currentState;
- (void)dealloc;
- (id)init;

@end

