/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PHStarkGenericTableViewCell.h"

@class NSLayoutConstraint, UIDateLabel, UIImageView, UILabel, VMVoicemail;

@interface PHStarkVoicemailTableViewCell : PHStarkGenericTableViewCell
{
    VMVoicemail *_representedVoicemail;
    UILabel *_nameLabel;
    NSLayoutConstraint *_nameLabelBaselineConstraint;
    UILabel *_pendingLabel;
    UIDateLabel *_dateLabel;
    UIImageView *_unreadIndicatorImageView;
}

@property(retain) UIImageView *unreadIndicatorImageView; // @synthesize unreadIndicatorImageView=_unreadIndicatorImageView;
@property(retain) UIDateLabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(retain) UILabel *pendingLabel; // @synthesize pendingLabel=_pendingLabel;
@property(retain) NSLayoutConstraint *nameLabelBaselineConstraint; // @synthesize nameLabelBaselineConstraint=_nameLabelBaselineConstraint;
@property(retain) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) VMVoicemail *representedVoicemail; // @synthesize representedVoicemail=_representedVoicemail;
- (void)setPendingState:(BOOL)arg1;
- (void)updatePendingState;
- (void)_voicemailFlagsDidChangeNotification:(id)arg1;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

