/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UITableViewCell.h"

@class UIImageView;

@interface PHStarkGenericTableViewCell : UITableViewCell
{
    BOOL _showsChevron;
    BOOL _hidesChevronWhenUnhighlighted;
    UIImageView *_chevronImageView;
}

@property(retain) UIImageView *chevronImageView; // @synthesize chevronImageView=_chevronImageView;
@property(nonatomic) BOOL hidesChevronWhenUnhighlighted; // @synthesize hidesChevronWhenUnhighlighted=_hidesChevronWhenUnhighlighted;
@property(nonatomic) BOOL showsChevron; // @synthesize showsChevron=_showsChevron;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

