/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "DialerLCDFieldProtocol.h"

@class UILabel;

@interface PHStarkInCallDialerLCDView : UIView <DialerLCDFieldProtocol>
{
    UILabel *_mainNumberLabel;
}

@property(retain) UILabel *mainNumberLabel; // @synthesize mainNumberLabel=_mainNumberLabel;
- (void)setLabel:(id)arg1;
- (id)name;
- (void)setName:(id)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (BOOL)highlighted;
- (void)setInCallMode:(BOOL)arg1;
- (BOOL)inCallMode;
- (struct CGSize)intrinsicContentSize;
- (void)setDelegate:(id)arg1;
- (void)deleteCharacter;
- (void)setText:(id)arg1 needsFormat:(BOOL)arg2;
- (id)text;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

