/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UITableViewCell.h"

#import "MPDetailSliderDelegate.h"
#import "PHAudioPlayerDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class NSArray, NSDate, NSLayoutConstraint, NSMutableArray, NSString, PHVoicemailSlider, UIActionSheet, UIButton, UIDateLabel, UIGestureRecognizer, UIImageView, UILabel, VMVoicemail;

@interface PHVoicemailCell : UITableViewCell <PHAudioPlayerDelegate, MPDetailSliderDelegate, UIActionSheetDelegate, UIGestureRecognizerDelegate>
{
    UIImageView *_unreadIndicatorView;
    UILabel *_nameLabel;
    UILabel *_labelLabel;
    UILabel *_durationLabel;
    UIButton *_infoButton;
    UIDateLabel *_dateLabel;
    UILabel *_longDateLabel;
    UIButton *_playPauseButton;
    PHVoicemailSlider *_sliderView;
    UIButton *_speakerButton;
    UIButton *_callBackButton;
    UIButton *_deleteButton;
    long _createConstraintsOnceToken;
    NSMutableArray *_calculatedConstraints;
    NSLayoutConstraint *_nameLabelYConstraint;
    NSLayoutConstraint *_labelLabelYConstraint;
    NSLayoutConstraint *_infoButtonXConstraint;
    NSLayoutConstraint *_infoButtonYConstraint;
    NSLayoutConstraint *_unreadIndicatorYConstraint;
    NSLayoutConstraint *_playPauseAndControlsYConstraint;
    NSLayoutConstraint *_buttonsYConstraint;
    BOOL _animatingUpdateToUnreadIndicator;
    BOOL _shouldReupdateUnreadIndicator;
    BOOL _playWhenAvailable;
    BOOL _trackingTouchInCloseVoicemailArea;
    UIGestureRecognizer *_closeVoicemailGestureRecognizer;
    BOOL _showingPlayController;
    VMVoicemail *_voicemail;
    id <PHVoicemailCellConfigurationDelegate> _configurationDelegate;
    id <PHVoicemailCellDelegate> _delegate;
    UIActionSheet *_audioSelectionActionSheet;
    NSArray *_audioSelectionActionSheetRoutes;
}

+ (BOOL)isRTLLanguage;
+ (float)heightShowingPlayControllerWithVoicemail:(id)arg1;
+ (float)contentViewHeightCollapsed;
+ (float)height;
+ (id)pauseImage;
+ (id)disabledPlayImage;
+ (id)playImage;
@property NSArray *audioSelectionActionSheetRoutes; // @synthesize audioSelectionActionSheetRoutes=_audioSelectionActionSheetRoutes;
@property UIActionSheet *audioSelectionActionSheet; // @synthesize audioSelectionActionSheet=_audioSelectionActionSheet;
@property(nonatomic) BOOL showingPlayController; // @synthesize showingPlayController=_showingPlayController;
@property(nonatomic) id <PHVoicemailCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) id <PHVoicemailCellConfigurationDelegate> configurationDelegate; // @synthesize configurationDelegate=_configurationDelegate;
@property(retain, nonatomic) VMVoicemail *voicemail; // @synthesize voicemail=_voicemail;
- (id)tableViewSeparatorColor;
- (void)trashButtonTapped:(id)arg1 withEvent:(id)arg2;
- (void)callButtonTapped:(id)arg1 withEvent:(id)arg2;
- (void)speakerButtonTapped:(id)arg1 withEvent:(id)arg2;
- (void)playPauseButtonTapped:(id)arg1 withEvent:(id)arg2;
- (void)customAccessoryButtonTapped:(id)arg1 withEvent:(id)arg2;
- (void)_closeVoicemailFromGestureRecognizerTap:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (BOOL)_pointIsInsideCloseVoicemailRect:(struct CGPoint)arg1;
- (id)_automationID;
- (void)_updatePlayPauseButton;
- (void)_updateUnreadIndicatorAnimated:(BOOL)arg1;
- (void)_updateUI;
- (void)_updateDurationLabel;
- (void)_updateProx;
- (void)_updateSpeakerButton;
- (void)_updatePlaybackTimer;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (void)layoutSubviews;
- (void)updateConstraints;
- (void)detailSlider:(id)arg1 didChangeValue:(float)arg2;
- (void)detailSliderTrackingDidCancel:(id)arg1;
- (void)detailSliderTrackingDidEnd:(id)arg1;
- (void)detailSliderTrackingDidBegin:(id)arg1;
- (void)stoppedPlayingWithDataSource:(id)arg1 withError:(id)arg2;
- (void)updateWithElapsedTime:(double)arg1 playableTime:(double)arg2 totalTime:(double)arg3 isPlaying:(BOOL)arg4 isPlayable:(BOOL)arg5 dataSource:(id)arg6;
- (void)startedPlayingWithDataSource:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)_handleContentSizeDidChange:(id)arg1;
- (void)_deregisterForVoicemailNotifications;
- (void)_registerForVoicemailNotifications;
- (void)_handleAudioControllerChanged:(id)arg1;
- (void)_handleVoicemailDataAvailableChanged:(id)arg1;
- (void)_handleVoicemailFlagsChanged:(id)arg1;
- (void)_handlePhoneAppAddressBookChanged:(id)arg1;
- (void)startPlaying;
- (struct CGPoint)anchorPointForUpdateInWindow:(id)arg1;
- (void)setShowingPlayController:(BOOL)arg1 animated:(BOOL)arg2;
@property(readonly) int audioButtonMode; // @dynamic audioButtonMode;
@property(readonly) BOOL unread; // @dynamic unread;
- (void)dealloc;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)_updateFonts;
@property(readonly, nonatomic) unsigned int playingStatus; // @dynamic playingStatus;
@property(readonly, nonatomic) NSString *dateLabelAccessabilityString; // @dynamic dateLabelAccessabilityString;
@property(readonly, nonatomic) NSDate *date; // @dynamic date;
@property(readonly, nonatomic) NSString *labelString; // @dynamic labelString;
@property(readonly, nonatomic) NSString *nameString; // @dynamic nameString;

@end

