/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

#import "MPDetailSliderDelegate.h"
#import "PHAudioPlayerDataSource.h"
#import "PHAudioPlayerDelegate.h"
#import "PHAudioRecorderDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSDictionary, NSIndexPath, NSLayoutConstraint, NSString, NSTimer, PHAudioPlayer, PHAudioRecorder, PHVoicemailSlider, UIButton, UIProgressView, UITableView, UIView;

@interface PHVoicemailGreetingViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, PHAudioRecorderDelegate, PHAudioPlayerDelegate, PHAudioPlayerDataSource, MPDetailSliderDelegate>
{
    UITableView *_tableView;
    UIView *_customView;
    UIView *_progressContainer;
    UIButton *_playStopButton;
    UIButton *_recordStopButton;
    PHVoicemailSlider *_slider;
    UIProgressView *_progressView;
    PHAudioRecorder *_greetingRecorder;
    PHAudioPlayer *_greetingPlayer;
    NSTimer *_greetingFetchTimeoutTimer;
    NSTimer *_greetingSaveTimeoutTimer;
    NSLayoutConstraint *_customViewButtonsYConstraint;
    NSLayoutConstraint *_customViewHeightConstraint;
    NSLayoutConstraint *_tableViewHeightConstraint;
    BOOL _hasAttemptedGreetingFetch;
    id _greetingFetchCompletion;
    BOOL _hasRecordedNewGreeting;
    id <PHVoicemailGreetingViewControllerDelegate> _greetingDelegate;
    NSIndexPath *_selectedIndexPath;
    int _greetingAudioState;
    int _greetingUIState;
    NSDictionary *_previousRoute;
    double _newGreetingDuration;
}

@property double newGreetingDuration; // @synthesize newGreetingDuration=_newGreetingDuration;
@property BOOL hasRecordedNewGreeting; // @synthesize hasRecordedNewGreeting=_hasRecordedNewGreeting;
@property(retain) NSDictionary *previousRoute; // @synthesize previousRoute=_previousRoute;
@property(nonatomic) int greetingUIState; // @synthesize greetingUIState=_greetingUIState;
@property(nonatomic) int greetingAudioState; // @synthesize greetingAudioState=_greetingAudioState;
@property(retain, nonatomic) NSIndexPath *selectedIndexPath; // @synthesize selectedIndexPath=_selectedIndexPath;
@property id <PHVoicemailGreetingViewControllerDelegate> greetingDelegate; // @synthesize greetingDelegate=_greetingDelegate;
- (void)_stopListeningForGreetingSaveNotifications;
- (void)_stopListeningForGreetingFetchNotifications;
- (void)_nukeStoredGreetingFile;
- (id)greetingTempFileLocation;
- (void)_updateForGreetingUIState;
- (void)_updateForGreetingAudioState;
- (void)_updateUI;
- (void)_updateFonts;
- (void)_handleContentSizeDidChange:(id)arg1;
- (void)_greetingSaveTimedOut;
- (void)_greetingSaveCompleted:(id)arg1;
- (void)_greetingFetchTimedOut;
- (void)_greetingFetchContinued:(id)arg1;
- (void)_greetingFetchBegan:(id)arg1;
- (void)_greetingFetchEnded:(id)arg1;
- (void)_recordStopButtonTapped:(id)arg1 withEvent:(id)arg2;
- (void)_playStopButtonTapped:(id)arg1 withEvent:(id)arg2;
- (void)_saveButtonTapped;
- (void)_cancelButtonTapped;
- (void)detailSliderTrackingDidCancel:(id)arg1;
- (void)detailSliderTrackingDidEnd:(id)arg1;
@property(readonly) BOOL fullFileAvailable;
@property(readonly) NSString *audioFilePath;
- (void)stoppedPlayingWithDataSource:(id)arg1 withError:(id)arg2;
- (void)updateWithElapsedTime:(double)arg1 playableTime:(double)arg2 totalTime:(double)arg3 isPlaying:(BOOL)arg4 isPlayable:(BOOL)arg5 dataSource:(id)arg6;
- (void)startedPlayingWithDataSource:(id)arg1;
- (void)audioRecorderEndedWithFile:(id)arg1 duration:(double)arg2 error:(id)arg3;
- (void)audioRecorderContinuedWithFile:(id)arg1 duration:(double)arg2;
- (void)audioRecorderStartedWithFile:(id)arg1;
@property(readonly) PHAudioPlayer *greetingPlayer;
@property(readonly) PHAudioRecorder *greetingRecorder;
- (void)setSelectedIndexPath:(id)arg1 animated:(BOOL)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)fetchGreetingInitial:(BOOL)arg1;
- (void)loadView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly) unsigned long long availableBytes;
@property(readonly) double duration;
@property(readonly) unsigned long long expectedTotalBytes;

@end

