/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UITableViewCell.h"

@class NSString, PHVoicemailListViewController<PHVoicemailListViewControllerConcrete>, UILabel;

@interface PHVoicemailFolderCell : UITableViewCell
{
    UILabel *_folderLabel;
    UILabel *_countLabel;
    PHVoicemailListViewController<PHVoicemailListViewControllerConcrete> *_viewController;
}

+ (float)height;
@property(retain, nonatomic) PHVoicemailListViewController<PHVoicemailListViewControllerConcrete> *viewController; // @synthesize viewController=_viewController;
- (void)_updateCount;
- (void)_handleContentSizeDidChange:(id)arg1;
- (void)_handleStoreChanged:(id)arg1;
- (void)prepareForReuse;
- (void)dealloc;
- (void)_updateFonts;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
@property(readonly, nonatomic) NSString *deletedText;

@end

