/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class NSArray, PHVoicemailCell, UIControl, UITableView;

@interface PHVoicemailListMaskView : UIView
{
    UIControl *_topGrayView;
    UIView *_topLineView;
    UIControl *_bottomGrayView;
    UIView *_bottomLineView;
    NSArray *_cellViewConstraints;
    NSArray *_lineConstraints;
    UITableView *_tableView;
    BOOL _showingGrayLayer;
    PHVoicemailCell *_cellToShow;
    id <PHVoicemailListMaskViewDelegate> _listMaskViewDelegate;
}

@property id <PHVoicemailListMaskViewDelegate> listMaskViewDelegate; // @synthesize listMaskViewDelegate=_listMaskViewDelegate;
@property(nonatomic) BOOL showingGrayLayer; // @synthesize showingGrayLayer=_showingGrayLayer;
@property(retain, nonatomic) PHVoicemailCell *cellToShow; // @synthesize cellToShow=_cellToShow;
- (void)_grayViewTouchUpInside:(id)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 forEvent:(struct __GSEvent *)arg2;
- (void)layoutSubviews;
- (void)updateConstraints;
- (void)recalculateMaskPosition;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 tableView:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

