/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PhoneViewController.h"

#import "ABUnknownPersonViewControllerDelegate.h"
#import "PHVoicemailCellDelegate.h"
#import "PHVoicemailListMaskViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSIndexPath, NSObject<OS_dispatch_group>, NSObject<OS_dispatch_queue>, PHVoicemailListMaskView, PHVoicemailNavigationController, UIGestureRecognizer, UITableView, VMVoicemail;

@interface PHVoicemailListViewController : PhoneViewController <PHVoicemailListMaskViewDelegate, ABUnknownPersonViewControllerDelegate, UIGestureRecognizerDelegate, PHVoicemailCellDelegate, UITableViewDataSource, UITableViewDelegate>
{
    PHVoicemailNavigationController *_navigationController;
    PHVoicemailListMaskView *_maskView;
    UITableView *_tableView;
    NSObject<OS_dispatch_queue> *_queue;
    int _disableUserInteractionCountLock;
    int _disableUserInteractionCount;
    int _isReloadingTableViewLock;
    BOOL _isReloadingTableView;
    BOOL _shouldReloadTableView;
    NSObject<OS_dispatch_queue> *_initialSetupQueue;
    int _isSettingUpLock;
    BOOL _isSettingUp;
    BOOL _reloadAfterInitialSetup;
    NSObject<OS_dispatch_group> *_loadingGroup;
    NSArray *_voicemails;
    NSArray *_childListViewControllersWithContent;
    BOOL _visible;
    BOOL _showingUnavailableCell;
    NSIndexPath *_detailIndexPath;
    VMVoicemail *_selectedVoicemail;
    UIGestureRecognizer *_navBarGestureRecognizer;
    UIGestureRecognizer *_leftBarButtonItemGestureRecognizer;
    UIGestureRecognizer *_rightBarButtonItemGestureRecognizer;
}

@property(retain) UIGestureRecognizer *rightBarButtonItemGestureRecognizer; // @synthesize rightBarButtonItemGestureRecognizer=_rightBarButtonItemGestureRecognizer;
@property(retain) UIGestureRecognizer *leftBarButtonItemGestureRecognizer; // @synthesize leftBarButtonItemGestureRecognizer=_leftBarButtonItemGestureRecognizer;
@property(retain) UIGestureRecognizer *navBarGestureRecognizer; // @synthesize navBarGestureRecognizer=_navBarGestureRecognizer;
@property(retain) NSArray *childListViewControllersWithContent; // @synthesize childListViewControllersWithContent=_childListViewControllersWithContent;
@property BOOL showingUnavailableCell; // @synthesize showingUnavailableCell=_showingUnavailableCell;
@property(retain) VMVoicemail *selectedVoicemail; // @synthesize selectedVoicemail=_selectedVoicemail;
@property(retain) NSIndexPath *detailIndexPath; // @synthesize detailIndexPath=_detailIndexPath;
@property BOOL visible; // @synthesize visible=_visible;
@property(retain) NSArray *voicemails; // @synthesize voicemails=_voicemails;
@property PHVoicemailNavigationController *navigationController; // @synthesize navigationController=_navigationController;
- (void)_updateUIForMaskViewChange;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)_handleNavBarTap:(id)arg1;
- (void)_enableInteraction;
- (void)_disableInteraction;
- (void)_reloadTableViewIfNecessary;
- (void)_performEfficientTableViewReloadWithVoicemails:(id)arg1 childListControllersWithContent:(id)arg2 showingUnavailableCell:(BOOL)arg3;
- (void)_forceCompleteTableViewReloadWithVoicemails:(id)arg1 childListControllersWithContent:(id)arg2 showingUnavailableCell:(BOOL)arg3;
- (void)_popOffIfNeeded;
- (id)_indexPathForItem:(id)arg1 inList:(id)arg2 offset:(int)arg3;
- (id)_indexPathsForItems:(id)arg1 inList:(id)arg2 offset:(int)arg3;
- (void)_updateTitle;
- (int)_firstVoicemailOffset;
- (void)unknownPersonViewController:(id)arg1 didResolveToPerson:(void *)arg2;
- (void)closeVoicemail;
- (void)maskViewWasTappedOutsideOfShownCell:(id)arg1;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (BOOL)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (id)contentScrollView;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
@property(readonly) BOOL shouldBeShown;
- (id)_fetchCurrentChildListViewControllersWithContent;
- (id)_fetchCurrentVoicemails;
- (void)_handleContentSizeDidChange:(id)arg1;
- (void)_voicemailUnavailableCellHeightChanged:(id)arg1;
- (void)_handleBackgroundNotification:(id)arg1;
- (void)_handleVoicemailListChanged:(id)arg1;
- (void)playVoicemail:(id)arg1;
- (void)dealloc;
- (id)initWithNavigationController:(id)arg1;

@end

