/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "TUAudioController.h"

@class AVController, NSArray, NSDictionary, NSNumber, NSObject<OS_dispatch_queue>, NSString;

@interface PHVoicemailAudioController : TUAudioController
{
    NSString *_category;
    AVController *_avController;
    NSObject<OS_dispatch_queue> *_avControllerQueue;
    NSObject<OS_dispatch_queue> *_pickableRoutesQueue;
    NSObject<OS_dispatch_queue> *_pickedRouteQueue;
    NSArray *_pickableRoutes;
    NSDictionary *_pickedRoute;
    NSDictionary *_forcedPickedRoute;
    BOOL _isRequestingPickableRoutes;
    BOOL _isRequestingPickedRoute;
    unsigned long long _lastPickableRoutesScheduleTime;
    unsigned long long _lastPickedRouteScheduleTime;
    NSNumber *_currentTimeOverride;
}

@property(retain) NSNumber *currentTimeOverride; // @synthesize currentTimeOverride=_currentTimeOverride;
- (void)_mediaServerDied:(id)arg1;
- (void)_pickableRoutesChanged:(id)arg1;
- (id)_pickableRoutesForceNewRequest:(BOOL)arg1;
- (id)_pickedRouteForceNewRequest:(BOOL)arg1;
- (void)_avControllerTimeJumpedAfterReset:(id)arg1;
@property double currentTime; // @dynamic currentTime;
@property(readonly) AVController *avController;
@property(readonly) NSDictionary *receiverRoute; // @dynamic receiverRoute;
@property(readonly) NSDictionary *speakerRoute; // @dynamic speakerRoute;
@property(readonly) int pickedRouteType; // @dynamic pickedRouteType;
- (int)typeForRoute:(id)arg1;
@property(copy, nonatomic) NSDictionary *pickedRoute; // @dynamic pickedRoute;
@property(readonly) NSArray *pickableRoutes; // @dynamic pickableRoutes;
- (void)dealloc;
- (id)initForVoicemailGreeting;
- (id)initForVoicemail;
- (id)_initWithCategory:(id)arg1;

@end

