/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UITableViewCell.h"

@class UILabel;

@interface PHVoicemailGreetingCell : UITableViewCell
{
    UILabel *_greetingTextLabel;
}

@property UILabel *greetingTextLabel; // @synthesize greetingTextLabel=_greetingTextLabel;
- (void)_updateFonts;
- (void)_handleContentSizeDidChange:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

