/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "MPDetailSlider.h"

@interface PHVoicemailSlider : MPDetailSlider
{
}

- (void)reset;
- (float)timeLabelVerticalOffsetForStyle:(int)arg1;
- (id)_modernThumbImageWithColor:(id)arg1 height:(float)arg2;
- (id)timeLabelTextColorForStyle:(int)arg1;
- (id)timeLabelFontForStyle:(int)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

