/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "PHVoicemailCellConfigurationDelegate.h"

@class NSArray, NSString;

@protocol PHVoicemailListViewControllerConcrete <PHVoicemailCellConfigurationDelegate>
@property(readonly) NSString *tableViewDestructiveActionText;
@property(readonly) BOOL popOffIfEmpty;
@property(readonly) unsigned int flagsNotToHave;
@property(readonly) unsigned int flagsToHave;
@property(readonly) NSString *folderName;
@property(readonly) NSString *navigationBarText;
- (void)performTableViewDestructiveActionForVoicemail:(id)arg1;

@optional
@property(readonly) NSArray *childListControllers;
@property(readonly) NSString *navigationBarTextWithCountFormat;
- (void)willShowVoicemails:(id)arg1;
@end

