/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIButton.h"

@class PHInCallRingView;

@interface SixSquareButton : UIButton
{
    struct UIEdgeInsets _contentInsets;
    PHInCallRingView *_ringView;
}

@property(retain) PHInCallRingView *ringView; // @synthesize ringView=_ringView;
- (void)setEnabled:(BOOL)arg1;
- (void)setSelected:(BOOL)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (void)setContentRect:(struct CGRect)arg1;
- (struct CGRect)imageRectForContentRect:(struct CGRect)arg1;
- (struct CGRect)titleRectForContentRect:(struct CGRect)arg1;
- (void)setupButton;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

