/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

@class SixSquareButton;

@interface SixSquareView : UIView
{
    SixSquareButton *_buttons[6];
    id _delegate;
    BOOL _onlyShowsFourButtons;
}

@property(nonatomic) BOOL onlyShowsFourButtons; // @synthesize onlyShowsFourButtons=_onlyShowsFourButtons;
- (void)setAllButtonsEnabled:(BOOL)arg1;
- (id)buttonAtPosition:(int)arg1;
- (void)_cancelButtonDown:(id)arg1;
- (void)_buttonDown:(id)arg1;
- (void)_buttonHeldDownShort:(id)arg1;
- (void)_buttonHeldDown:(id)arg1;
- (void)_buttonClicked:(id)arg1;
- (void)setTitle:(id)arg1 image:(id)arg2 selectedImage:(id)arg3 forPosition:(int)arg4;
- (void)setDelegate:(id)arg1;
- (void)removeFromSuperview;
- (struct CGSize)totalSize;
- (struct CGSize)intrinsicContentSize;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

