/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIViewController.h"

@interface UIViewController (Testing)
+ (int)tabViewType;
- (void)transitionCompleted;
- (void)_finishSwitchTest;
- (BOOL)runTest:(id)arg1 options:(id)arg2;
- (void)willStartTest:(id)arg1;
@end

