/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "CommunicationDisplayViewController.h"

#import "PhoneBaseViewController.h"

@class AudioDeviceController, CNFCallViewController;

@interface VideoConferenceController : CommunicationDisplayViewController <PhoneBaseViewController>
{
    CNFCallViewController *_faceTimeCallViewController;
    AudioDeviceController *_audioDeviceController;
}

+ (int)statusBarStyle;
+ (id)defaultPNGName;
+ (int)viewType;
@property(readonly, nonatomic) CNFCallViewController *faceTimeCallViewController; // @synthesize faceTimeCallViewController=_faceTimeCallViewController;
- (BOOL)shouldHideStatusBar;
- (BOOL)isShowingFaceTimeUI;
- (void)resetToFullScreenPreview;
- (void)setIsSendingVideo:(BOOL)arg1;
- (void)stopPreview;
- (void)startPreview;
- (void)cleanUpForIncomingCall;
- (void)cleanUpVideoConference;
- (void)slideBarsInAnimated:(BOOL)arg1;
- (void)fadeInAnimated:(BOOL)arg1 completionBlock:(id)arg2;
- (void)fadeOutAnimated:(BOOL)arg1 completionBlock:(id)arg2;
- (void)faceTimeEndedWhileSuspending;
- (void)faceTimeEnded;
- (void)restoreInCallUIAndAudioRoute;
- (void)_restoreInCallUIAndAudioRoute;
- (void)animateOutOfCallWaitingAlert;
- (void)animateToCallWaitingAlert;
- (BOOL)isCallWaitingViewVisible;
- (void)_handleInvitation:(id)arg1;
- (void)_updateInterfaceSizeAndOrientation;
- (void)transitionInFromViewType:(int)arg1 animated:(BOOL)arg2 completionBlock:(id)arg3;
- (void)prepareForTransitionInFromViewType:(int)arg1 animated:(BOOL)arg2;
- (void)transitionFromLockScreenAnimated:(BOOL)arg1;
- (void)transitionToLockScreenAnimated:(BOOL)arg1;
- (void)_didFinishLocking;
- (id)_lockScreenImageView;
- (BOOL)isShowingLock;
- (void)handleURL:(id)arg1;
- (void)prepareToHandleURL:(id)arg1;
- (void)_applicationReactivated:(id)arg1;
- (void)prepareForSnapshot;
- (BOOL)shouldSnapshot;
- (BOOL)shouldDisableEdgeClip;
- (void)dealloc;
- (void)unloadViewForced:(BOOL)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidUnload;
- (void)loadView;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)updateViewControllerForOrientation:(int)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (BOOL)automaticallyForwardAppearanceAndRotationMethodsToChildViewControllers;
- (void)_ensureFaceTimeCallViewControllerExists;
- (id)init;

@end

