/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "VMVoicemail.h"

@interface VMVoicemail (MobilePhone)
@property(readonly) BOOL hasCallbackNumber;
@property(readonly) BOOL hasValidLabel;
- (void)setRead;
- (void)moveFromTrash;
- (void)moveToTrash;
- (void)deleteForever;
- (void)callBack;
@end

